ERROR:tornado.application:Uncaught exception GET /api/status/1 (127.0.0.1)
HTTPRequest(protocol='http', host='tornado', method='GET', uri='/api/status/1', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'X-Scheme': 'http', 'Host': 'tornado', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0', 'Connection': 'close', 'Cookie': '__utma=56341038.691215668.1404420352.1404420352.1404420352.1; __utmz=56341038.1404420352.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _xsrf=2|9bbaf545|53983bad45a00cc5862ad6c09f4ff045|1404478820; Magica="2|1:0|10:1404491231|6:Magica|4:MQ==|6527b904dbd5f16fc28df03e4b51c6d5439b00929e2008897ac5cc248674825f"; Moe="2|1:0|10:1404491231|3:Moe|8:Um9vdA==|d219c0cc5f743ea36e0d514cace31406d4634f40136d58e8c519380067ceb336"', 'X-Real-Ip': '127.0.0.1'})
Traceback (most recent call last):
  File "/home/magimagi/.local/pypy-2.3.1-linux64/site-packages/tornado/web.py", line 1346, in _when_complete
    callback()
  File "/home/magimagi/.local/pypy-2.3.1-linux64/site-packages/tornado/web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "uoj.py", line 139, in get
    self.write(i.status)
  File "/home/magimagi/.local/pypy-2.3.1-linux64/site-packages/tornado/web.py", line 661, in write
    chunk = utf8(chunk)
  File "/home/magimagi/.local/pypy-2.3.1-linux64/site-packages/tornado/escape.py", line 203, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <type 'long'>
ERROR:tornado.access:500 GET /api/status/1 (127.0.0.1) 3.28ms
ERROR:tornado.application:Uncaught exception GET /api/result/1 (127.0.0.1)
HTTPRequest(protocol='http', host='tornado', method='GET', uri='/api/result/1', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'X-Scheme': 'http', 'Host': 'tornado', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0', 'Connection': 'close', 'Cookie': '__utma=56341038.691215668.1404420352.1404420352.1404420352.1; __utmz=56341038.1404420352.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _xsrf=2|9bbaf545|53983bad45a00cc5862ad6c09f4ff045|1404478820; Magica="2|1:0|10:1404491231|6:Magica|4:MQ==|6527b904dbd5f16fc28df03e4b51c6d5439b00929e2008897ac5cc248674825f"; Moe="2|1:0|10:1404491231|3:Moe|8:Um9vdA==|d219c0cc5f743ea36e0d514cace31406d4634f40136d58e8c519380067ceb336"', 'X-Real-Ip': '127.0.0.1'})
Traceback (most recent call last):
  File "/home/magimagi/.local/pypy-2.3.1-linux64/site-packages/tornado/web.py", line 1346, in _when_complete
    callback()
  File "/home/magimagi/.local/pypy-2.3.1-linux64/site-packages/tornado/web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "uoj.py", line 145, in get
    self.write(json.dump(i.__dict__))
TypeError: dump() takes at least 2 arguments (1 given)
ERROR:tornado.access:500 GET /api/result/1 (127.0.0.1) 2.65ms
